version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://backend:8000}
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL:-ws://backend:8000}
    depends_on:
      - backend
    networks:
      - vibecaas-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@db:5432/vibecaas}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
    depends_on:
      - db
      - redis
    networks:
      - vibecaas-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vibecaas
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - vibecaas-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - vibecaas-network

volumes:
  postgres_data:

networks:
  vibecaas-network:
    driver: bridge