global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: vibecaas-backend
    static_configs:
      - targets: ["backend:8000"]
    metrics_path: /metrics

  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

