apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    
  - name: DCGM
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: true
    jsonData:
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: jaeger
          url: http://jaeger:16686/trace/$${__value.raw}