apiVersion: apps/v1
kind: Deployment
metadata:
  name: vibecaas-backend
  namespace: vibecaas
  labels:
    app: vibecaas-backend
    component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vibecaas-backend
  template:
    metadata:
      labels:
        app: vibecaas-backend
        component: backend
    spec:
      serviceAccountName: vibecaas-backend
      containers:
      - name: backend
        image: vibecaas/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: vibecaas-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: vibecaas-secrets
              key: redis-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: vibecaas-secrets
              key: secret-key
        - name: K8S_IN_CLUSTER
          value: "true"
        - name: K8S_NAMESPACE
          value: "vibecaas-apps"
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: vibecaas-backend
  namespace: vibecaas
  labels:
    app: vibecaas-backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: vibecaas-backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vibecaas-backend
  namespace: vibecaas
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vibecaas-backend
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vibecaas-backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vibecaas-backend
subjects:
- kind: ServiceAccount
  name: vibecaas-backend
  namespace: vibecaas