apiVersion: v1
kind: Namespace
metadata:
  name: vibecaas
  labels:
    name: vibecaas
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vibecaas-backend
  namespace: vibecaas
  labels:
    app: vibecaas-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vibecaas-backend
  template:
    metadata:
      labels:
        app: vibecaas-backend
    spec:
      containers:
      - name: backend
        image: vibecaas/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: vibecaas-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: vibecaas-secrets
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: vibecaas-secrets
              key: jwt-secret
        - name: NVIDIA_CLOUD_API_KEY
          valueFrom:
            secretKeyRef:
              name: vibecaas-secrets
              key: nvidia-api-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: vibecaas-backend-service
  namespace: vibecaas
spec:
  selector:
    app: vibecaas-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vibecaas-frontend
  namespace: vibecaas
  labels:
    app: vibecaas-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vibecaas-frontend
  template:
    metadata:
      labels:
        app: vibecaas-frontend
    spec:
      containers:
      - name: frontend
        image: vibecaas/frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "https://api.vibecaas.com"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: vibecaas-frontend-service
  namespace: vibecaas
spec:
  selector:
    app: vibecaas-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP